### PR TITLE
feat: adds viewing own storage purchases

### PR DESCRIPTION
**Pull request by jurajpiar**
Populates the my purchases page, adds an agreement service and a context to handle its data.

Solves https://rsklabs.atlassian.net/browse/RMKT-329

Also adds a temporary `createReducer` function to replace the `storeReducerFactory` one that needs its typing fixed.

### CODE REVIEW

**Comment by julianmrodri** [comment]
LGTM. -

**Review by julianmrodri — APPROVED** [review]
LGTM - There are issues with amounts/conversions as discussed but can tackle accross the whole app

**Comment by julianmrodri** [comment]
Would like @farinalvaro  to review as well.

**Review by farinalvaro — APPROVED** [review]
lgtm

**Pull request merged**
