### PR TITLE
feat(devops): adding cd fix for staging branch

### PR DESCRIPTION
**Pull request by rafaiovlabs**
The CD workflow must be added to the proper branch in order to execute correctly.

### CODE REVIEW

**Comment by artem-brazhnikov** [comment]
@rafaiovlabs I want to revisit one question we have already discussed here: https://github.com/rsksmart/rif-marketplace-ui/pull/745/files#r592971714. So imagine that the QA are testing on staging a new feature from the staging branch. But the master contains the code for release, like now for example. And as soon as we create a new tag - it will re-deploy the same version to the staging which will downgrade it and break QA experience. How do you think we can handle it? Maybe we should delete tags deployment for staging and add tags with postfix to testnet only?

**Review by rafaiovlabs — COMMENTED** [review]
When this PR is merded the automatic deployment will work under these circumstances:
* if on "staging" branch a new tag is added with the form v #.#.# or v #.#.#-word. then the deploy will be automatic

**Comment by rafaiovlabs** [comment]
> @rafaiovlabs I want to revisit one question we have already discussed here: https://github.com/rsksmart/rif-marketplace-ui/pull/745/files#r592971714. So imagine that the QA are testing on staging a new feature from the staging branch. But the master contains the code for release, like now for example. And as soon as we create a new tag - it will re-deploy the same version to the staging which will downgrade it and break QA experience. How do you think we can handle it? Maybe we should delete tags deployment for staging and add tags with postfix to testnet only?

I'm ok with with whatever workflow fits your needs. the use case you mention can be overcome by the development process itself but ok already changed it, we will have tags only for testnet then. regards.

**Comment by artem-brazhnikov** [comment]
> > @rafaiovlabs I want to revisit one question we have already discussed here: https://github.com/rsksmart/rif-marketplace-ui/pull/745/files#r592971714. So imagine that the QA are testing on staging a new feature from the staging branch. But the master contains the code for release, like now for example. And as soon as we create a new tag - it will re-deploy the same version to the staging which will downgrade it and break QA experience. How do you think we can handle it? Maybe we should delete tags deployment for staging and add tags with postfix to testnet only?
> 
> I'm ok with with whatever workflow fits your needs. the use case you mention can be overcome by the development process itself but ok already changed it, we will have tags only for testnet then. regards.

Thank you, Rafael.

**Review by artem-brazhnikov — APPROVED** [review]

**Review by jurajpiar — APPROVED** [review]

**Pull request merged**
