### PR TITLE
RBTC Buy and Plausible to Master

### PR DESCRIPTION
**Pull request by artem-brazhnikov**
Merge changes of rbtc fix and plausible to master before the mainnet release

### CODE REVIEW

**Comment by jurajpiar** [comment]
Let's wait for [the deploy fix PR](https://github.com/rsksmart/rif-marketplace-ui/pull/802) to get merged to staging first.

**Review by jurajpiar — APPROVED** [review]

**Review by jurajpiar — CHANGES_REQUESTED** [review]
Just noticed the commit history is a bit unhappy, not following [the conventions](https://www.conventionalcommits.org/en/v1.0.0/). For example the commit message "Hotfix/rns buy rbtc (#787)".
Also it contains lot of commits that don't actually run so I'll squash those into one and rename this one.

**Comment by artem-brazhnikov** [comment]
> Just noticed the commit history is a bit unhappy, not following [the conventions](https://www.conventionalcommits.org/en/v1.0.0/). For example the commit message "Hotfix/rns buy rbtc (#787)".
> Also it contains lot of commits that don't actually run so I'll squash those into one and rename this one.

thanks. that was a squash commit

**Review by jurajpiar — APPROVED** [review]
v1.3.5

**Review by nduchak — APPROVED** [review]
LGTM

**Pull request merged**
